type: object
additionalProperties: false
description: A Workflow object
properties:
  type:
    const: workflow
    type: string
  id:
    examples:
      - wfl_3JqAR9ddLRVZLK5z4yD8oeHB
    type: string
  attributes:
    properties:
      status:
        description: |-
          The status of the Workflow

          Possible values:
          - paused
          - running
          - archived

          Do not assume this is a static enumeration; Persona may add new
          values in the future without a versioned update.
        type: string
      name:
        type: string
      created-at:
        examples:
          - '2022-08-08T18:55:44.910Z'
        type: string
        format: date-time
    type: object
    additionalProperties: false
  relationships:
    type: object
    additionalProperties: false
    properties:
      latest-published-version:
        type: object
        description: latest published version
        additionalProperties: false
        properties:
          data:
            type: object
            additionalProperties: false
            properties:
              type:
                const: workflow-version
                type: string
              id:
                type: string
      active-deployment:
        type: object
        description: latest active deployment
        additionalProperties: false
        properties:
          data:
            oneOf:
              - type: 'null'
              - $ref: ./workflow-deployment.yaml
            unevaluatedProperties: false
